web:
  image: registry.demo.opsta.co.th/petclinic
  tag: dev
  logging: DEBUG
  replicas: 1
  commitId: CHANGE_COMMIT_ID
  version: release
  weightRelease: 100
  weightCanary: 0
  imagePullSecrets: nexus-credential
  imagePullPolicy: Always
  requestCpu: 500m
db:
  image: mariadb
  tag: 10.3.6
  requestCpu: 500m
credential:
  mysqlRootPassword: rootpass
  mysqlDatabase: petclinic
  mysqlUser: petuser
  mysqlPassword: petpass
  mysqlPort: 3306
