web:
  image: registry.demo.opsta.co.th/petclinic
  tag: latest
  logging: INFO
  replicas: 2
  commitId: CHANGE_COMMIT_ID
  version: release
  imagePullSecrets: nexus-credential
  imagePullPolicy: Always
  requestCpu: 1000m
db:
  image: mariadb
  tag: 10.3.6
  requestCpu: 1000m
credential:
  mysqlRootPassword: prodrootpass
  mysqlDatabase: prodpetclinic
  mysqlUser: prodpetuser
  mysqlPassword: prodpetpass
  mysqlPort: 3306
