web:
  image: registry.demo.opsta.co.th/petclinic
  tag: uat
  logging: INFO
  replicas: 2
  commitId: CHANGE_COMMIT_ID
  version: release
  imagePullSecrets: nexus-credential
  imagePullPolicy: Always
  requestCpu: 500m
db:
  image: mariadb
  tag: 10.4.8-bionic
  requestCpu: 500m
credential:
  mysqlRootPassword: uatrootpass
  mysqlDatabase: uatpetclinic
  mysqlUser: uatpetuser
  mysqlPassword: uatpetpass
  mysqlPort: 3306
