web:
  image: registry.demo.opsta.co.th/petclinic
  tag: latest
  logging: DEBUG
  replicas: 1
  commitId: CHANGE_COMMIT_ID
  imagePullSecrets: nexus-credential
db:
  image: mariadb
  tag: 10.3.6
credential:
  mysqlRootPassword: rootpass
  mysqlDatabase: petclinic
  mysqlUser: petuser
  mysqlPassword: petpass
  mysqlPort: 3306
