{{- if ne .Values.web.version "canary" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  ports:
    - port: {{ .Values.credential.mysqlPort }}
  selector:
    app: {{ .Release.Name }}-db
{{- end }}
